# Generated by Django 3.1.2 on 2020-10-14 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('rbts', '0001_initial'), ('rbts', '0002_redditcredential_owner'), ('rbts', '0003_auto_20201014_0214'), ('rbts', '0004_auto_20201014_0217'), ('rbts', '0005_auto_20201014_0219'), ('rbts', '0006_auto_20201014_0221'), ('rbts', '0007_auto_20201014_0249')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('client_id', models.CharField(max_length=256)),
                ('client_secret', models.CharField(max_length=256)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('USERNAME', 'subreddit'), ('USERNAME', 'username')], default='USERNAME', max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbts.botcredentials')),
            ],
        ),
    ]
