# Generated by Django 3.1.2 on 2020-10-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbts', '0003_auto_20201014_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditcredential',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added'),
        ),
    ]
