# Generated by Django 3.1.2 on 2020-10-14 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbts', '0004_auto_20201014_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditcredential',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
