# Generated by Django 3.1.2 on 2020-10-14 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbts', '0005_auto_20201014_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditcredential',
            name='owner',
        ),
        migrations.AddField(
            model_name='redditcredential',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
