# Generated by Django 3.1.2 on 2020-10-14 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbts', '0006_auto_20201014_0221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedditCredential',
            new_name='BotCredentials',
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('USERNAME', 'subreddit'), ('USERNAME', 'username')], default='USERNAME', max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbts.botcredentials')),
            ],
        ),
    ]
